# Redis Configuration for Caching
version: '3.8'

services:
  redis-cluster:
    image: redis:7-alpine
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - attendance-network

  redis-sentinel:
    image: redis:7-alpine
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
    networks:
      - attendance-network
    depends_on:
      - redis-cluster

  # CDN and Caching Layer
  nginx-cache:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/var/cache/nginx
    networks:
      - attendance-network

  # Varnish Cache
  varnish:
    image: varnish:stable
    ports:
      - "8081:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    environment:
      - VARNISH_SIZE=1G
    networks:
      - attendance-network

volumes:
  redis-data:

networks:
  attendance-network:
    external: true

