version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SQL_SERVER_PASSWORD:-TestPassword123}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_MEMORY_LIMIT_MB: 1024
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SQL_SERVER_PASSWORD:-TestPassword123}' -C -Q 'SELECT 1' -l 30"]
      interval: 30s
      timeout: 20s
      retries: 30
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: src/backend/gateways/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=WaaedTest;User Id=sa;Password=${SQL_SERVER_PASSWORD:-TestPassword123};TrustServerCertificate=true;Connection Timeout=60;Command Timeout=300;
      - ENABLE_RABBITMQ_HEALTH_CHECK=false
      - ENABLE_REDIS_HEALTH_CHECK=false
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_SHUTDOWNTIMEOUTSECONDS=30
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health --connect-timeout 10 --max-time 20 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 20
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

networks:
  default:
    name: waaed-e2e-network
