services:
  # Database
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sql_staging_data:/var/opt/mssql
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_staging_data:/data
    networks:
      - waaed-staging-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: src/backend/gateways/Dockerfile
    ports:
      - "5100:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Authentication Service
  authentication-service:
    build:
      context: .
      dockerfile: src/backend/services/Authentication/Dockerfile
    ports:
      - "5101:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Attendance Service
  attendance-service:
    build:
      context: .
      dockerfile: src/backend/services/Attendance/Dockerfile
    ports:
      - "5102:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Face Recognition Service
  face-recognition-service:
    build:
      context: .
      dockerfile: src/backend/services/FaceRecognition/Dockerfile
    ports:
      - "5103:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Leave Management Service
  leave-management-service:
    build:
      context: .
      dockerfile: src/backend/services/LeaveManagement/Dockerfile
    ports:
      - "5104:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Workflow Engine Service
  workflow-engine:
    build:
      context: .
      dockerfile: src/backend/services/WorkflowEngine/Dockerfile
    ports:
      - "5110:80"
    env_file:
      - .env.staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - sql-server
      - redis
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Voice Recognition Service - DISABLED: Dockerfile not available
  # voice-recognition-service:
  #   build:
  #     context: .
  #     dockerfile: src/backend/services/VoiceRecognition/Dockerfile
  #   ports:
  #     - "5113:80"
  #   env_file:
  #     - .env.staging
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Staging
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
  #     - ENCRYPTION_KEY=${ENCRYPTION_KEY}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - ConnectionStrings__Redis=redis:6379
  #   depends_on:
  #     - sql-server
  #     - redis
  #   networks:
  #     - waaed-staging-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # Compliance Service - DISABLED: Dockerfile not available
  # compliance-service:
  #   build:
  #     context: .
  #     dockerfile: src/backend/services/Compliance/Dockerfile
  #   ports:
  #     - "5114:80"
  #   env_file:
  #     - .env.staging
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Staging
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
  #     - ENCRYPTION_KEY=${ENCRYPTION_KEY}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - ConnectionStrings__Redis=redis:6379
  #   depends_on:
  #     - sql-server
  #     - redis
  #   networks:
  #     - waaed-staging-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # Business Intelligence Service - DISABLED: Dockerfile not available
  # business-intelligence-service:
  #   build:
  #     context: .
  #     dockerfile: src/backend/services/BusinessIntelligence/Dockerfile
  #   ports:
  #     - "5106:80"
  #   env_file:
  #     - .env.staging
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Staging
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=Server=sql-server;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE}
  #     - ENCRYPTION_KEY=${ENCRYPTION_KEY}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - ConnectionStrings__Redis=redis:6379
  #   depends_on:
  #     - sql-server
  #     - redis
  #   networks:
  #     - waaed-staging-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # Frontend
  frontend:
    build:
      context: src/frontend/attendancepro-frontend
      dockerfile: Dockerfile
    ports:
      - "3100:80"
    environment:
      - VITE_API_BASE_URL=http://staging-api.waaed.sa/api
      - NODE_ENV=staging
    depends_on:
      - api-gateway
    networks:
      - waaed-staging-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy for staging domain
  nginx-staging:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - frontend
    networks:
      - waaed-staging-network
    command: >
      sh -c "echo '
      server {
          listen 80;
          server_name staging-api.waaed.sa;
          
          location /api/ {
              proxy_pass http://api-gateway:80/;
              proxy_set_header Host $$host;
              proxy_set_header X-Real-IP $$remote_addr;
              proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $$scheme;
          }
          
          location / {
              proxy_pass http://frontend:80/;
              proxy_set_header Host $$host;
              proxy_set_header X-Real-IP $$remote_addr;
              proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $$scheme;
          }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_staging_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - waaed-staging-network

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3101:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_staging_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - waaed-staging-network

volumes:
  sql_staging_data:
  redis_staging_data:
  prometheus_staging_data:
  grafana_staging_data:

networks:
  waaed-staging-network:
    driver: bridge
