apiVersion: v2
name: waaed
description: A comprehensive unified education platform
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://waaed.sa/favicon.ico
keywords:
  - education
  - lms
  - finance
  - hr
  - library
home: https://waaed.sa
sources:
  - https://github.com/Alsairy/Waaed
maintainers:
  - name: Waaed Team
    email: support@waaed.sa
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

