name: production
url: https://api.waaed.sa
protection_rules:
  required_reviewers:
    - Alsairy
  prevent_self_review: true
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  required_status_checks:
    strict: true
    contexts:
      - "ci-cd-pipeline"
      - "security-scan"
      - "code-quality"
      - "database-migrations"
      - "testing"
  wait_timer: 5
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
variables:
  ENVIRONMENT: production
  API_URL: https://api.waaed.sa
  DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
  REDIS_URL: ${{ secrets.PRODUCTION_REDIS_URL }}
secrets:
  - PRODUCTION_DATABASE_URL
  - PRODUCTION_REDIS_URL
  - PRODUCTION_JWT_SECRET
  - PRODUCTION_ENCRYPTION_KEY
  - SLACK_WEBHOOK_URL
  - EMAIL_SMTP_PASSWORD
