#!/bin/bash


echo "Generating secure secrets for Hudur..."

JWT_SECRET=$(openssl rand -base64 48 | tr -d "=+/" | cut -c1-64)

DB_PASSWORD=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-32)

REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-32)

GRAFANA_PASSWORD=$(openssl rand -base64 12 | tr -d "=+/" | cut -c1-16)

ENCRYPTION_KEY=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-32)

cat > .env.production << EOF

DB_SERVER=sql-server
DB_NAME=Hudur
DB_USER=sa
DB_PASSWORD=${DB_PASSWORD}
DB_TRUST_SERVER_CERTIFICATE=true

JWT_SECRET_KEY=${JWT_SECRET}
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=7d

REDIS_URL=redis://redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

API_GATEWAY_PORT=5000
CORS_ORIGINS=https://yourdomain.com,https://app.yourdomain.com

AUTH_SERVICE_PORT=5001
ATTENDANCE_SERVICE_PORT=5002
FACE_RECOGNITION_SERVICE_PORT=5003
LEAVE_MANAGEMENT_SERVICE_PORT=5004
ANALYTICS_SERVICE_PORT=5005
BI_SERVICE_PORT=5006
NOTIFICATIONS_SERVICE_PORT=5007
WEBHOOKS_SERVICE_PORT=5008
INTEGRATIONS_SERVICE_PORT=5009
WORKFLOW_SERVICE_PORT=5010
COLLABORATION_SERVICE_PORT=5011
EVENT_SOURCING_SERVICE_PORT=5012

GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
PROMETHEUS_PORT=9090
GRAFANA_PORT=3001

SMTP_HOST=smtp.yourdomain.com
SMTP_PORT=587
SMTP_USER=noreply@yourdomain.com
SMTP_PASSWORD=CHANGE_THIS_SMTP_PASSWORD_IN_PRODUCTION
SMTP_FROM_NAME=Hudur System

SMS_PROVIDER=twilio
SMS_ACCOUNT_SID=CHANGE_THIS_SMS_SID_IN_PRODUCTION
SMS_AUTH_TOKEN=CHANGE_THIS_SMS_TOKEN_IN_PRODUCTION
SMS_FROM_NUMBER=+1234567890

STORAGE_TYPE=local
STORAGE_PATH=/app/uploads
AWS_ACCESS_KEY_ID=CHANGE_THIS_AWS_KEY_IN_PRODUCTION
AWS_SECRET_ACCESS_KEY=CHANGE_THIS_AWS_SECRET_IN_PRODUCTION
AWS_BUCKET_NAME=hudur-uploads
AWS_REGION=us-east-1

FACE_RECOGNITION_CONFIDENCE_THRESHOLD=0.85
FACE_RECOGNITION_MODEL_PATH=/app/models/face_recognition

MICROSOFT_CLIENT_ID=CHANGE_THIS_MICROSOFT_CLIENT_ID
MICROSOFT_CLIENT_SECRET=CHANGE_THIS_MICROSOFT_CLIENT_SECRET
GOOGLE_CLIENT_ID=CHANGE_THIS_GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=CHANGE_THIS_GOOGLE_CLIENT_SECRET
SALESFORCE_CLIENT_ID=CHANGE_THIS_SALESFORCE_CLIENT_ID
SALESFORCE_CLIENT_SECRET=CHANGE_THIS_SALESFORCE_CLIENT_SECRET

ENCRYPTION_KEY=${ENCRYPTION_KEY}
RATE_LIMIT_REQUESTS_PER_MINUTE=100
ACCOUNT_LOCKOUT_ATTEMPTS=5
ACCOUNT_LOCKOUT_DURATION_MINUTES=30

LOG_LEVEL=Information
LOG_TO_FILE=true
LOG_FILE_PATH=/app/logs/hudur.log
LOG_MAX_FILE_SIZE_MB=100
LOG_MAX_FILES=10

HEALTH_CHECK_TIMEOUT_SECONDS=30
HEALTH_CHECK_INTERVAL_SECONDS=60

CONNECTION_POOL_SIZE=100
QUERY_TIMEOUT_SECONDS=30
CACHE_EXPIRATION_MINUTES=60
EOF

echo "✅ Secrets generated successfully!"
echo "📁 Generated .env.production with secure secrets"
echo ""
echo "🔐 Generated secrets:"
echo "   JWT Secret: ${JWT_SECRET:0:10}... (64 chars)"
echo "   DB Password: ${DB_PASSWORD:0:8}... (32 chars)"
echo "   Redis Password: ${REDIS_PASSWORD:0:8}... (32 chars)"
echo "   Grafana Password: ${GRAFANA_PASSWORD:0:6}... (16 chars)"
echo "   Encryption Key: ${ENCRYPTION_KEY:0:8}... (32 chars)"
echo ""
echo "⚠️  IMPORTANT: Store these secrets securely and never commit them to version control!"
echo "⚠️  Update the remaining placeholder values in .env.production before deployment"
