apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hudur.fullname" . }}-config
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
data:
  # Database configuration
  ConnectionStrings__DefaultConnection: {{ include "hudur.databaseConnectionString" . | quote }}
  
  # Redis configuration
  Redis__ConnectionString: {{ include "hudur.redisConnectionString" . | quote }}
  
  # JWT configuration
  Jwt__Key: {{ .Values.config.jwt.key | quote }}
  Jwt__Issuer: {{ .Values.config.jwt.issuer | quote }}
  Jwt__Audience: {{ .Values.config.jwt.audience | quote }}
  Jwt__ExpiryMinutes: {{ .Values.config.jwt.expiryMinutes | quote }}
  
  # Email configuration
  EmailSettings__SmtpServer: {{ .Values.config.email.smtpServer | quote }}
  EmailSettings__SmtpPort: {{ .Values.config.email.smtpPort | quote }}
  EmailSettings__EnableSsl: {{ .Values.config.email.enableSsl | quote }}
  EmailSettings__FromEmail: {{ .Values.config.email.fromEmail | quote }}
  EmailSettings__FromName: {{ .Values.config.email.fromName | quote }}
  
  # SMS configuration
  SmsSettings__Provider: {{ .Values.config.sms.provider | quote }}
  
  # Logging configuration
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  
  # CORS configuration
  AllowedHosts: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hudur.fullname" . }}-secrets
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT key (base64 encoded)
  jwt-key: {{ .Values.config.jwt.key | b64enc | quote }}
  
  # Database password (base64 encoded)
  {{- if .Values.postgresql.enabled }}
  database-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  
  # Email password (base64 encoded)
  email-password: {{ .Values.config.email.password | default "" | b64enc | quote }}
  
  # SMS auth token (base64 encoded)
  sms-auth-token: {{ .Values.config.sms.authToken | default "" | b64enc | quote }}
  
  # Firebase server key (base64 encoded)
  firebase-server-key: {{ .Values.config.pushNotifications.firebase.serverKey | default "" | b64enc | quote }}

